FROM node:14.17.1-alpine3.13

WORKDIR /var/www/buycoin/frontend

COPY package*.json ./

RUN npm install
RUN npm cache clean -f
RUN npm cache verify
RUN npm install -g react-scripts
RUN npm audit fix

COPY . .
